In [1]:
import pandas as pd
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn import metrics

In [2]:
table_test_1 = pd.read_excel("predictions_test_1.xlsx", index_col="Unnamed: 0")

table_test_1.head()

,Filename,label,Multibranch_predict - train 1,Multibranch_proba_ - train 1,Multibranch_predict - train 2,Multibranch_proba - train 2,PointNet_predict - train 1,PointNet_proba_ - train 1,PointNet_predict - train 2,PointNet_proba_ - train 2,Catboost_Predicted_Label_train1,Catboost_proba - train 1,Catboost_Predicted_Label_train2,Catboost_proba - train 2,Age
0,TG6986.edf,0,0,1.314773e-34,0,5.423912e-18,0,0.046852,0,0.090399,0,0.062559,0,0.178602,40
1,TG1776.edf,0,0,5.254600e-41,0,3.611208e-06,0,0.037963,0,0.096153,0,0.104491,0,0.484829,58
2,TG8367.edf,0,0,1.367010e-38,0,9.311546e-10,0,0.032953,0,0.085485,0,0.051893,0,0.082078,38
3,TG2420.edf,0,0,8.809311e-20,0,2.436424e-08,0,0.038257,0,0.091874,0,0.045615,0,0.106287,33
4,TG9493.edf,0,0,3.626747e-18,0,1.003309e-08,0,0.041165,0,0.084416,0,0.062842,0,0.101288,63

In [3]:
table_test_2 = pd.read_excel("predictions_test_2.xlsx", index_col="Unnamed: 0")

table_test_2.head()

,Filename,label,Multibranch_predict - train 1,Multibranch_proba - train 1,Multibranch_predict - train 2,Multibranch_proba - train 2,PointNet_predict - train 1,PointNet_proba - train 1,PointNet_predict - train 2,PointNet_proba - train 2,Catboost_Predicted_Label_train1,Catboost_proba - train 1,Catboost_Predicted_Label_train2,Catboost_proba - train 2,Age
0,TG9127.edf,0,0,6.762778e-31,1,9.748360e-01,0,0.031391,0,0.156642,0,0.047847,0,0.376926,29
1,TG9076.edf,0,0,7.381166e-23,0,1.521971e-14,0,0.086491,0,0.242265,0,0.072457,1,0.528130,59
2,TG778.edf,0,0,2.263973e-05,1,1.000000e+00,0,0.055559,0,0.206246,0,0.045047,0,0.272386,64
3,TG10338.edf,0,0,1.078816e-04,0,1.711457e-02,0,0.030081,0,0.372648,0,0.096961,1,0.649641,66
4,TG2361.edf,0,0,8.939560e-31,0,1.762271e-10,0,0.029591,0,0.236523,0,0.122702,0,0.447866,20

In [4]:
def score_printer(header, col_name, table):
    confusion = confusion_matrix(table['label'], table[col_name])
    print(f"Multibranch score - {header}")
    # print(f"Precision: {round(precision_score(table['label'], table[col_name], average='binary'), 2)}")
    # print(f"Recall: {round(recall_score(table['label'], table[col_name], average='binary'), 2)}")
    # print(f"F1 Score: {round(f1_score(table['label'], table[col_name], average='binary'), 2)}")
    # print(f"Accuracy: {round(accuracy_score(table['label'], table[col_name]), 2)}")

    total=sum(sum(confusion))
    Accuracy = (confusion[0,0]+confusion[1,1])/total
    Specificity = confusion[0,0]/(confusion[0,0]+confusion[0,1])
    Sensitivity = confusion[1,1]/(confusion[1,0]+confusion[1,1])
    Precision = confusion[1,1]/(confusion[0,1]+confusion[1,1])
    Recall = confusion[1,1]/(confusion[1,0]+confusion[1,1]) 
    F1 = 2 * (Precision * Recall) / (Precision + Recall)
    print(f"Precision: {round(Precision, 2)}")
    print(f"Recall: {round(Recall, 2)}")
    print(f"F1 Score: {round(F1, 2)}")
    print(f"Accuracy: {round(Accuracy, 2)}")
    print(f"Specificity: {round(Specificity, 2)}")
    print(f"Sensitivity: {round(Sensitivity, 2)}")

In [5]:
col_name = 'Multibranch_predict - train 1'
header = "train 1, test 1"
score_printer(header, col_name, table_test_1)

Multibranch score - train 1, test 1
Precision: 0.56
Recall: 0.52
F1 Score: 0.54
Accuracy: 0.92
Specificity: 0.96
Sensitivity: 0.52

In [6]:
for table, table_name in [(table_test_1, "test_1"), (table_test_2, "test_2")]:
    for col_name in ["Multibranch_predict - train 1", "Multibranch_predict - train 2"]:
        header = col_name.split("- ")[-1] + " " + table_name
        score_printer(header, col_name, table)
        print("--------------------------")

Multibranch score - train 1 test_1
Precision: 0.56
Recall: 0.52
F1 Score: 0.54
Accuracy: 0.92
Specificity: 0.96
Sensitivity: 0.52
--------------------------
Multibranch score - train 2 test_1
Precision: 0.3
Recall: 0.83
F1 Score: 0.44
Accuracy: 0.82
Specificity: 0.82
Sensitivity: 0.83
--------------------------
Multibranch score - train 1 test_2
Precision: 0.94
Recall: 0.52
F1 Score: 0.67
Accuracy: 0.75
Specificity: 0.97
Sensitivity: 0.52
--------------------------
Multibranch score - train 2 test_2
Precision: 0.79
Recall: 0.83
F1 Score: 0.81
Accuracy: 0.81
Specificity: 0.78
Sensitivity: 0.83
--------------------------